<a href="https://colab.research.google.com/github/AbhinavKumar07/C124/blob/main/C124.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
A = [2, 4, 4, 6, 9, 3]
print(A)

print(A[4])

[2, 4, 4, 6, 9, 3]
9


In [9]:
B = [[1,4,6], [3,4,9] , [2,6,8]]
print(B)

print(B[0][0])
print(B[2][2])

[[1, 4, 6], [3, 4, 9], [2, 6, 8]]
1
8


In [4]:
import numpy as np

a = np.array([3,5,6,3,86])
print(a)

print(type(a))

[ 3  5  6  3 86]
<class 'numpy.ndarray'>


In [10]:
a_2d = np.array([[3,4,32],['abhinav',16,True],[24,68,39]])
print(a_2d)
print(a_2d[1][0])

[['3' '4' '32']
 ['abhinav' '16' 'True']
 ['24' '68' '39']]
abhinav


In [6]:
cities = np.array(["Bangalore", "Delhi" , "San Franscisco"])
print(cities[1])

Delhi


In [11]:
a_2d = np.array([[3,4,32],['abhinav',16,True],[24,68,39]])
a_2d[2,2] = 100
print(a_2d)

[['3' '4' '32']
 ['abhinav' '16' 'True']
 ['24' '68' '100']]


In [12]:
x = np.array([[2,5] , [45,33]])
y = np.array([[23,54] , [445,333]])

rows = 2
cols = 2

z = [[0,0],[0,0]]

for i in range(rows):
  for j in range(cols):
    z[i][j] = x[i][j] + y[i][j]

print(x,"\n")
print(y,"\n")
print(z)

[[ 2  5]
 [45 33]] 

[[ 23  54]
 [445 333]] 

[[25, 59], [490, 366]]


In [15]:
x_1 = np.array([[234,43],[456,54]])
y_1 = np.array([[123,45],[678,90]])

rows = 2
columns = 2

z_1 = [[0,0],[0,0]]

for r in range(rows):
  for c in range(columns):
    z_1[r][c] = x_1[r][c] - y_1[r][c]

print(x_1 , "\n")
print(y_1 , "\n")
print(z_1)

[[234  43]
 [456  54]] 

[[123  45]
 [678  90]] 

[[111, -2], [-222, -36]]
